In [23]:
import pandas as pd
#df = pd.read_csv("Titanic.csv")
from config import data_path
def read_file(file_path):
    df= pd.read_csv(file_path)
    return df

read_file(data_path)

ImportError: cannot import name 'data_path' from 'config' (x:\Desktop\AI_depi\ML-depi\Depi-CA-S2S7-AI\src\DA\session-3\code\config.py)

In [24]:
df= pd.read_csv("Titanic.csv")

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
#df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
from config import cols_drop
df.drop(cols_drop,axis=1,inplace=True)

In [14]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [16]:
#cols_drop=['PassengerId','Name','Ticket']
#df.drop(cols_drop,axis=1,inplace=True)

In [ ]:
from config import cols_drop
def drop_cols(df:pd.DataFrame,cols:list[str])->pd.DataFrame:
    
    return df.drop(columns=cols)

In [30]:
dtype=df.dtypes
nunique= df.nunique()
pd.DataFrame({"dtype":dtype, "nunique":nunique}).T

        Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
dtype      int64  int64  str  float64  int64  int64  float64   str      str
nunique        2      3    2       88      7      7      248   147        3

In [ ]:
cols=["Survived",'Pclass','Sex','Age','SibSp','Parch']
df[cols]=df[cols].astype("category")

In [32]:
def get_data_info(df):
    return pd.DataFrame({"dtype":df.dtype, "nunique":df.nunique()}).T

In [38]:
null=df.isnull().sum()
ratio=(null/891)*100
print(ratio)
pd.DataFrame({"Null":null,"ratio":ratio}).T

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [34]:
df.info(
)

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    category
 1   Pclass    891 non-null    category
 2   Sex       891 non-null    category
 3   Age       714 non-null    category
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    str
 8   Embarked  889 non-null    str
dtypes: category(4), float64(1), int64(2), str(2)
memory usage: 39.2 KB

In [39]:
df=df.dropna(subset=['Embarked'])

In [40]:
df=df.drop("Cabin",axis=1)

In [41]:
df.describe()

            SibSp       Parch        Fare
count  889.000000  889.000000  889.000000
mean     0.524184    0.382452   32.096681
std      1.103705    0.806761   49.697504
min      0.000000    0.000000    0.000000
25%      0.000000    0.000000    7.895800
50%      0.000000    0.000000   14.454200
75%      1.000000    0.000000   31.000000
max      8.000000    6.000000  512.329200

In [43]:
madian=df["Age"].median()
df['Age']=df["Age"].fillna(madian)

TypeError: 'Categorical' with dtype category does not support operation 'median'

In [44]:
null=df.isnull().sum()
ratio=(null/891)*100
print(ratio)
pd.DataFrame({"Null":null,"ratio":ratio}).T

Survived     0.00000
Pclass       0.00000
Sex          0.00000
Age         19.86532
SibSp        0.00000
Parch        0.00000
Fare         0.00000
Embarked     0.00000
dtype: float64

       Survived  Pclass  Sex        Age  SibSp  Parch  Fare  Embarked
Null        0.0     0.0  0.0  177.00000    0.0    0.0   0.0       0.0
ratio       0.0     0.0  0.0   19.86532    0.0    0.0   0.0       0.0

In [45]:
def null_info(df):
    null=df.isnull().sum()
    ratio=(null/df.shape[0])*100
    return pd.DataFrame({"Null":null,"ratio":ratio}).T